CREATE SCHEMA conect24;
use conect24;

CREATE TABLE PERFIL (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    BIO TEXT NULL,
    DATA_NASC DATE NULL,
    FOTO VARCHAR(2048) NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE POSTAGEM (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, -- CABEM MAIS NUMEROS, É POSITIVO
    PERFIL_ID BIGINT UNSIGNED NOT NULL, -- CHAVE ESTRANGEIRA
    TEXTO TEXT NULL,
    IMAGEM VARCHAR(2048) NULL,
    RESPONDE_PARA_ID BIGINT UNSIGNED NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL(ID) ON DELETE CASCADE, -- COISAS ASSOCIADAS SERÃO DELETADAS AUTOMATICAMENTE
    FOREIGN KEY (RESPONDE_PARA_ID) REFERENCES POSTAGEM(ID) ON DELETE SET NULL -- SE DELETA O PAI ENTÃO A FILHA FICA NULA
);

